homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 52.34923
  longitude: -1.279892
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 114
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/London

# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:

http:
  # Uncomment this to add a password (recommended!)
  api_password: dilbert99
  # Uncomment this if you are using SSL or running in Docker etc
  # base_url: example.duckdns.org:8123

# Checks for available updates
updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
#conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

# Weather Prediction
sensor:
  platform: yr

# Text to speech
#tts:
#  platform: google

# configuration for emulated Hue (for Alexa discovery)
emulated_hue:
  type: alexa
  host_ip: 192.168.1.99
  listen_port: 8300
  off_maps_to_on_domains:
    - script
    - scene
  expose_by_default: true
  exposed_domains:
    - switch

# New section GJN
# Lounge TV
#shell_command:
#  loungetv_on: /home/hass/scripts/loungetv.sh on
#  loungetv_off: /home/hass/scripts/loungetv.sh off


switch:
  platform: command_line
  switches:
    lounge_tv:
      friendly_name: TV
      command_on: "/bin/bash /home/hass/scripts/loungetv.sh on"
      command_off: "/bin/bash /home/hass/scripts/loungetv.sh off"

  customize:
    switch.lounge_tv:
      icon: mdi:television


